const DATA = [
  {
    id: 0,
    title: "IPhone 11",
    comp: "Havels",
    price: 750.0,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
    img: "/images/tab.jpg",
    img1: "/images/tab1.jpg",
  },
  {
    id: 1,
    title: "IPhone 11 Pro Max",
    comp: "Havels",
    price: 800.0,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
    img: "/images/iphone12pro.png",
    img1: "/images/iphone12promax.png",
  },
  {
    id: 2,
    title: "IPhone 12 Mini",
    comp: "Havels",
    price: 950.0,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
    img: "/images/iphone12.png",
    img1: "/images/iphone12mini.png",
  },
  {
    id: 3,
    title: "IPhone 12",
    comp: "Havels",
    price: 1050.0,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
    img: "/images/tab2.jpg",
    img1: "/images/tab3.jpg",
  },
  {
    id: 4,
    title: "IPhone 12",
    comp: "Havels",
    price: 1050.0,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
    img: "/images/tab2.jpg",
    img1: "/images/tab3.jpg",
  },
  {
    id: 5,
    title: "IPhone 12",
    comp: "Havels",
    price: 1050.0,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
    img: "/images/tab2.jpg",
    img1: "/images/tab3.jpg",
  },
  {
    id: 6,
    title: "IPhone 12",
    comp: "Havels",
    price: 1050.0,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
    img: "/images/tab2.jpg",
    img1: "/images/tab3.jpg",
  },
  {
    id: 7,
    title: "IPhone 12",
    comp: "Havels",
    price: 1050.0,
    desc: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source.",
    img: "/images/tab2.jpg",
    img1: "/images/tab3.jpg",
  },
];

export default DATA;
